name: API

env:

  CF_USER: ${{ secrets.CF_USER }}
  CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
  CF_SPACE: ${{ secrets.CF_SPACE }}
  CF_API: ${{ secrets.CF_API }}
  CF_ORG: ${{ secrets.CF_ORG  }}
  PINBOARD_TOKEN: ${{ secrets.PINBOARD_TOKEN }}
  ARTIFACTORY_API_TOKEN_SECRET: ${{ secrets.ARTIFACTORY_API_TOKEN_SECRET }}
  ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME  }}
  ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD  }}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2
          restore-keys: ${{ runner.os }}-m2

      - name: Build the application
        run: mvn -e -Dspring.profiles.active=production verify deploy

#       - name: Deploy to Cloud Foundry
#         run: |
#           cd $GITHUB_WORKSPACE
#           ./deploy/cf.sh
#           ./deploy/deploy.sh
